"""Protocol constants that are fixed independently of experiment outcomes."""

from __future__ import annotations

NBAIOT_CLIENT_IDS = tuple(f"nb{i:02d}" for i in range(1, 10))
NBAIOT_EXPECTED_FEATURES = 115
NBAIOT_EXPECTED_SOURCE_CLIENTS = 9
DIAD_EXPECTED_FEATURES = 86
DIAD_EXPECTED_SOURCE_CLIENTS = 105
DIAD_MINIMUM_ELIGIBLE_CLIENTS = 10
ATTACK_DEVELOPMENT_SEED = 9001
SHRINKAGE_N0_CANDIDATES = (100, 300, 1000, 3000, 10000)
SUPERVISED_THRESHOLD_CANDIDATES = 1000
